[tool.poetry]
name = "nipanel-python"
version = "0.1.0"
description = "NI Panel Python API"
authors = ["NI <opensource@ni.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
grpcio = {version=">=1.49.0,<2.0", optional=true}
protobuf = {version=">=4.21", optional=true}

[tool.poetry.group.codegen.dependencies]
grpcio-tools = [
  {version = "1.49.1", python = ">=3.9,<3.12"},
  {version = "1.59.0", python = ">=3.12,<3.13"},
  {version = "1.67.0", python = "^3.13"},
]
mypy-protobuf = ">=3.4"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
