"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ConnectRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PANEL_ID_FIELD_NUMBER: builtins.int
    PANEL_URI_FIELD_NUMBER: builtins.int
    panel_id: builtins.str
    """Unique ID of the panel"""
    panel_uri: builtins.str
    """Absolute path of the panel's file on disk, or network path to the file"""
    def __init__(
        self,
        *,
        panel_id: builtins.str = ...,
        panel_uri: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["panel_id", b"panel_id", "panel_uri", b"panel_uri"]) -> None: ...

global___ConnectRequest = ConnectRequest

@typing.final
class ConnectResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ConnectResponse = ConnectResponse

@typing.final
class DisconnectRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PANEL_ID_FIELD_NUMBER: builtins.int
    panel_id: builtins.str
    """Unique ID of the panel"""
    def __init__(
        self,
        *,
        panel_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["panel_id", b"panel_id"]) -> None: ...

global___DisconnectRequest = DisconnectRequest

@typing.final
class DisconnectResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___DisconnectResponse = DisconnectResponse

@typing.final
class GetValueRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PANEL_ID_FIELD_NUMBER: builtins.int
    VALUE_ID_FIELD_NUMBER: builtins.int
    panel_id: builtins.str
    """Unique ID of the panel"""
    value_id: builtins.str
    """Unique ID of value"""
    def __init__(
        self,
        *,
        panel_id: builtins.str = ...,
        value_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["panel_id", b"panel_id", "value_id", b"value_id"]) -> None: ...

global___GetValueRequest = GetValueRequest

@typing.final
class GetValueResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    @property
    def value(self) -> google.protobuf.any_pb2.Any:
        """The value"""

    def __init__(
        self,
        *,
        value: google.protobuf.any_pb2.Any | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["value", b"value"]) -> None: ...

global___GetValueResponse = GetValueResponse

@typing.final
class SetValueRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PANEL_ID_FIELD_NUMBER: builtins.int
    VALUE_ID_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    panel_id: builtins.str
    """Unique ID of the panel"""
    value_id: builtins.str
    """Unique ID of the value"""
    @property
    def value(self) -> google.protobuf.any_pb2.Any:
        """The value"""

    def __init__(
        self,
        *,
        panel_id: builtins.str = ...,
        value_id: builtins.str = ...,
        value: google.protobuf.any_pb2.Any | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["panel_id", b"panel_id", "value", b"value", "value_id", b"value_id"]) -> None: ...

global___SetValueRequest = SetValueRequest

@typing.final
class SetValueResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___SetValueResponse = SetValueResponse
