"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import ni.pythonpanel.v1.python_panel_service_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class PythonPanelServiceStub:
    """Service interface for interacting with python panels"""

    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    StartPanel: grpc.UnaryUnaryMultiCallable[
        ni.pythonpanel.v1.python_panel_service_pb2.StartPanelRequest,
        ni.pythonpanel.v1.python_panel_service_pb2.StartPanelResponse,
    ]
    """Start a panel (or connect to if it has already been started)
    Status Codes for errors:
    - INVALID_ARGUMENT: 
      - The panel script filename doesn't end in .py.
      - The panel identifier contains invalid characters. Only alphanumeric characters and underscores are allowed.
    - NOT_FOUND: 
      - The panel script file was not found.
      - The python executable file was not found.
    """

    StopPanel: grpc.UnaryUnaryMultiCallable[
        ni.pythonpanel.v1.python_panel_service_pb2.StopPanelRequest,
        ni.pythonpanel.v1.python_panel_service_pb2.StopPanelResponse,
    ]
    """Stop a panel
    Status Codes for errors:
    - INVALID_ARGUMENT:
      - The panel identifier contains invalid characters. Only alphanumeric characters and underscores are allowed.
    """

    EnumeratePanels: grpc.UnaryUnaryMultiCallable[
        ni.pythonpanel.v1.python_panel_service_pb2.EnumeratePanelsRequest,
        ni.pythonpanel.v1.python_panel_service_pb2.EnumeratePanelsResponse,
    ]
    """Enumerate the panels available in the system, including information about the state of the panels and what values they have.
    Status Codes for errors:
    """

    GetValue: grpc.UnaryUnaryMultiCallable[
        ni.pythonpanel.v1.python_panel_service_pb2.GetValueRequest,
        ni.pythonpanel.v1.python_panel_service_pb2.GetValueResponse,
    ]
    """Get a value for a control on the panel
    Status Codes for errors:
    - INVALID_ARGUMENT: 
      - The panel identifier contains invalid characters. Only alphanumeric characters and underscores are allowed.
      - The value identifier contains invalid characters. Only alphanumeric characters and underscores are allowed.
    - NOT_FOUND: 
      - The value with the specified identifier was not found.
    """

    TryGetValue: grpc.UnaryUnaryMultiCallable[
        ni.pythonpanel.v1.python_panel_service_pb2.TryGetValueRequest,
        ni.pythonpanel.v1.python_panel_service_pb2.TryGetValueResponse,
    ]
    """Try to get a value for a control on the panel
    Status Codes for errors:
    - INVALID_ARGUMENT: 
      - The panel identifier contains invalid characters. Only alphanumeric characters and underscores are allowed.
      - The value identifier contains invalid characters. Only alphanumeric characters and underscores are allowed.
    """

    SetValue: grpc.UnaryUnaryMultiCallable[
        ni.pythonpanel.v1.python_panel_service_pb2.SetValueRequest,
        ni.pythonpanel.v1.python_panel_service_pb2.SetValueResponse,
    ]
    """Set a value for a control on the panel
    Status Codes for errors:
    - INVALID_ARGUMENT: 
      - The panel identifier contains invalid characters. Only alphanumeric characters and underscores are allowed.
      - The value identifier contains invalid characters. Only alphanumeric characters and underscores are allowed.
    """

class PythonPanelServiceAsyncStub:
    """Service interface for interacting with python panels"""

    StartPanel: grpc.aio.UnaryUnaryMultiCallable[
        ni.pythonpanel.v1.python_panel_service_pb2.StartPanelRequest,
        ni.pythonpanel.v1.python_panel_service_pb2.StartPanelResponse,
    ]
    """Start a panel (or connect to if it has already been started)
    Status Codes for errors:
    - INVALID_ARGUMENT: 
      - The panel script filename doesn't end in .py.
      - The panel identifier contains invalid characters. Only alphanumeric characters and underscores are allowed.
    - NOT_FOUND: 
      - The panel script file was not found.
      - The python executable file was not found.
    """

    StopPanel: grpc.aio.UnaryUnaryMultiCallable[
        ni.pythonpanel.v1.python_panel_service_pb2.StopPanelRequest,
        ni.pythonpanel.v1.python_panel_service_pb2.StopPanelResponse,
    ]
    """Stop a panel
    Status Codes for errors:
    - INVALID_ARGUMENT:
      - The panel identifier contains invalid characters. Only alphanumeric characters and underscores are allowed.
    """

    EnumeratePanels: grpc.aio.UnaryUnaryMultiCallable[
        ni.pythonpanel.v1.python_panel_service_pb2.EnumeratePanelsRequest,
        ni.pythonpanel.v1.python_panel_service_pb2.EnumeratePanelsResponse,
    ]
    """Enumerate the panels available in the system, including information about the state of the panels and what values they have.
    Status Codes for errors:
    """

    GetValue: grpc.aio.UnaryUnaryMultiCallable[
        ni.pythonpanel.v1.python_panel_service_pb2.GetValueRequest,
        ni.pythonpanel.v1.python_panel_service_pb2.GetValueResponse,
    ]
    """Get a value for a control on the panel
    Status Codes for errors:
    - INVALID_ARGUMENT: 
      - The panel identifier contains invalid characters. Only alphanumeric characters and underscores are allowed.
      - The value identifier contains invalid characters. Only alphanumeric characters and underscores are allowed.
    - NOT_FOUND: 
      - The value with the specified identifier was not found.
    """

    TryGetValue: grpc.aio.UnaryUnaryMultiCallable[
        ni.pythonpanel.v1.python_panel_service_pb2.TryGetValueRequest,
        ni.pythonpanel.v1.python_panel_service_pb2.TryGetValueResponse,
    ]
    """Try to get a value for a control on the panel
    Status Codes for errors:
    - INVALID_ARGUMENT: 
      - The panel identifier contains invalid characters. Only alphanumeric characters and underscores are allowed.
      - The value identifier contains invalid characters. Only alphanumeric characters and underscores are allowed.
    """

    SetValue: grpc.aio.UnaryUnaryMultiCallable[
        ni.pythonpanel.v1.python_panel_service_pb2.SetValueRequest,
        ni.pythonpanel.v1.python_panel_service_pb2.SetValueResponse,
    ]
    """Set a value for a control on the panel
    Status Codes for errors:
    - INVALID_ARGUMENT: 
      - The panel identifier contains invalid characters. Only alphanumeric characters and underscores are allowed.
      - The value identifier contains invalid characters. Only alphanumeric characters and underscores are allowed.
    """

class PythonPanelServiceServicer(metaclass=abc.ABCMeta):
    """Service interface for interacting with python panels"""

    @abc.abstractmethod
    def StartPanel(
        self,
        request: ni.pythonpanel.v1.python_panel_service_pb2.StartPanelRequest,
        context: _ServicerContext,
    ) -> typing.Union[ni.pythonpanel.v1.python_panel_service_pb2.StartPanelResponse, collections.abc.Awaitable[ni.pythonpanel.v1.python_panel_service_pb2.StartPanelResponse]]:
        """Start a panel (or connect to if it has already been started)
        Status Codes for errors:
        - INVALID_ARGUMENT: 
          - The panel script filename doesn't end in .py.
          - The panel identifier contains invalid characters. Only alphanumeric characters and underscores are allowed.
        - NOT_FOUND: 
          - The panel script file was not found.
          - The python executable file was not found.
        """

    @abc.abstractmethod
    def StopPanel(
        self,
        request: ni.pythonpanel.v1.python_panel_service_pb2.StopPanelRequest,
        context: _ServicerContext,
    ) -> typing.Union[ni.pythonpanel.v1.python_panel_service_pb2.StopPanelResponse, collections.abc.Awaitable[ni.pythonpanel.v1.python_panel_service_pb2.StopPanelResponse]]:
        """Stop a panel
        Status Codes for errors:
        - INVALID_ARGUMENT:
          - The panel identifier contains invalid characters. Only alphanumeric characters and underscores are allowed.
        """

    @abc.abstractmethod
    def EnumeratePanels(
        self,
        request: ni.pythonpanel.v1.python_panel_service_pb2.EnumeratePanelsRequest,
        context: _ServicerContext,
    ) -> typing.Union[ni.pythonpanel.v1.python_panel_service_pb2.EnumeratePanelsResponse, collections.abc.Awaitable[ni.pythonpanel.v1.python_panel_service_pb2.EnumeratePanelsResponse]]:
        """Enumerate the panels available in the system, including information about the state of the panels and what values they have.
        Status Codes for errors:
        """

    @abc.abstractmethod
    def GetValue(
        self,
        request: ni.pythonpanel.v1.python_panel_service_pb2.GetValueRequest,
        context: _ServicerContext,
    ) -> typing.Union[ni.pythonpanel.v1.python_panel_service_pb2.GetValueResponse, collections.abc.Awaitable[ni.pythonpanel.v1.python_panel_service_pb2.GetValueResponse]]:
        """Get a value for a control on the panel
        Status Codes for errors:
        - INVALID_ARGUMENT: 
          - The panel identifier contains invalid characters. Only alphanumeric characters and underscores are allowed.
          - The value identifier contains invalid characters. Only alphanumeric characters and underscores are allowed.
        - NOT_FOUND: 
          - The value with the specified identifier was not found.
        """

    @abc.abstractmethod
    def TryGetValue(
        self,
        request: ni.pythonpanel.v1.python_panel_service_pb2.TryGetValueRequest,
        context: _ServicerContext,
    ) -> typing.Union[ni.pythonpanel.v1.python_panel_service_pb2.TryGetValueResponse, collections.abc.Awaitable[ni.pythonpanel.v1.python_panel_service_pb2.TryGetValueResponse]]:
        """Try to get a value for a control on the panel
        Status Codes for errors:
        - INVALID_ARGUMENT: 
          - The panel identifier contains invalid characters. Only alphanumeric characters and underscores are allowed.
          - The value identifier contains invalid characters. Only alphanumeric characters and underscores are allowed.
        """

    @abc.abstractmethod
    def SetValue(
        self,
        request: ni.pythonpanel.v1.python_panel_service_pb2.SetValueRequest,
        context: _ServicerContext,
    ) -> typing.Union[ni.pythonpanel.v1.python_panel_service_pb2.SetValueResponse, collections.abc.Awaitable[ni.pythonpanel.v1.python_panel_service_pb2.SetValueResponse]]:
        """Set a value for a control on the panel
        Status Codes for errors:
        - INVALID_ARGUMENT: 
          - The panel identifier contains invalid characters. Only alphanumeric characters and underscores are allowed.
          - The value identifier contains invalid characters. Only alphanumeric characters and underscores are allowed.
        """

def add_PythonPanelServiceServicer_to_server(servicer: PythonPanelServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
