# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ni/pythonpanel/v1/python_panel_types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*ni/pythonpanel/v1/python_panel_types.proto\x12\x11ni.pythonpanel.v1\" \n\x0e\x42oolCollection\x12\x0e\n\x06values\x18\x01 \x03(\x08\"&\n\x14\x42yteStringCollection\x12\x0e\n\x06values\x18\x01 \x03(\x0c\"!\n\x0f\x46loatCollection\x12\x0e\n\x06values\x18\x01 \x03(\x01\"\x1f\n\rIntCollection\x12\x0e\n\x06values\x18\x01 \x03(\x12\"\"\n\x10StringCollection\x12\x0e\n\x06values\x18\x01 \x03(\tB\x9a\x01\n\x15\x63om.ni.pythonpanel.v1B\x17PythonPanelServiceProtoP\x01Z\rpythonpanelv1\xf8\x01\x01\xa2\x02\x04NIPP\xaa\x02\"NationalInstruments.PythonPanel.V1\xca\x02\x11NI\\PythonPanel\\V1\xea\x02\x13NI::PythonPanel::V1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ni.pythonpanel.v1.python_panel_types_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025com.ni.pythonpanel.v1B\027PythonPanelServiceProtoP\001Z\rpythonpanelv1\370\001\001\242\002\004NIPP\252\002\"NationalInstruments.PythonPanel.V1\312\002\021NI\\PythonPanel\\V1\352\002\023NI::PythonPanel::V1'
  _BOOLCOLLECTION._serialized_start=65
  _BOOLCOLLECTION._serialized_end=97
  _BYTESTRINGCOLLECTION._serialized_start=99
  _BYTESTRINGCOLLECTION._serialized_end=137
  _FLOATCOLLECTION._serialized_start=139
  _FLOATCOLLECTION._serialized_end=172
  _INTCOLLECTION._serialized_start=174
  _INTCOLLECTION._serialized_end=205
  _STRINGCOLLECTION._serialized_start=207
  _STRINGCOLLECTION._serialized_end=241
# @@protoc_insertion_point(module_scope)
