"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class StartPanelRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PANEL_ID_FIELD_NUMBER: builtins.int
    PANEL_SCRIPT_PATH_FIELD_NUMBER: builtins.int
    PYTHON_PATH_FIELD_NUMBER: builtins.int
    panel_id: builtins.str
    """Unique ID of the panel"""
    panel_script_path: builtins.str
    """Absolute path of the panel script's file on disk, or network path to the file"""
    python_path: builtins.str
    """Path to the python interpreter to use for the panel script."""
    def __init__(
        self,
        *,
        panel_id: builtins.str = ...,
        panel_script_path: builtins.str = ...,
        python_path: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["panel_id", b"panel_id", "panel_script_path", b"panel_script_path", "python_path", b"python_path"]) -> None: ...

global___StartPanelRequest = StartPanelRequest

@typing.final
class StartPanelResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PANEL_URL_FIELD_NUMBER: builtins.int
    panel_url: builtins.str
    """Location of the panel's webpage"""
    def __init__(
        self,
        *,
        panel_url: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["panel_url", b"panel_url"]) -> None: ...

global___StartPanelResponse = StartPanelResponse

@typing.final
class StopPanelRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PANEL_ID_FIELD_NUMBER: builtins.int
    RESET_FIELD_NUMBER: builtins.int
    panel_id: builtins.str
    """Unique ID of the panel"""
    reset: builtins.bool
    """Reset all storage associated with panel"""
    def __init__(
        self,
        *,
        panel_id: builtins.str = ...,
        reset: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["panel_id", b"panel_id", "reset", b"reset"]) -> None: ...

global___StopPanelRequest = StopPanelRequest

@typing.final
class StopPanelResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___StopPanelResponse = StopPanelResponse

@typing.final
class EnumeratePanelsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___EnumeratePanelsRequest = EnumeratePanelsRequest

@typing.final
class PanelInformation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PANEL_ID_FIELD_NUMBER: builtins.int
    PANEL_URL_FIELD_NUMBER: builtins.int
    VALUE_IDS_FIELD_NUMBER: builtins.int
    panel_id: builtins.str
    """Unique ID of the panel"""
    panel_url: builtins.str
    """Location of the panel's webpage"""
    @property
    def value_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """IDs of all of the values associated with the panel"""

    def __init__(
        self,
        *,
        panel_id: builtins.str = ...,
        panel_url: builtins.str = ...,
        value_ids: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["panel_id", b"panel_id", "panel_url", b"panel_url", "value_ids", b"value_ids"]) -> None: ...

global___PanelInformation = PanelInformation

@typing.final
class EnumeratePanelsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PANELS_FIELD_NUMBER: builtins.int
    @property
    def panels(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PanelInformation]:
        """The list of panels available in the system"""

    def __init__(
        self,
        *,
        panels: collections.abc.Iterable[global___PanelInformation] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["panels", b"panels"]) -> None: ...

global___EnumeratePanelsResponse = EnumeratePanelsResponse

@typing.final
class TryGetValueRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PANEL_ID_FIELD_NUMBER: builtins.int
    VALUE_ID_FIELD_NUMBER: builtins.int
    panel_id: builtins.str
    """Unique ID of the panel"""
    value_id: builtins.str
    """Unique ID of value"""
    def __init__(
        self,
        *,
        panel_id: builtins.str = ...,
        value_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["panel_id", b"panel_id", "value_id", b"value_id"]) -> None: ...

global___TryGetValueRequest = TryGetValueRequest

@typing.final
class TryGetValueResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    @property
    def value(self) -> google.protobuf.any_pb2.Any:
        """The value, if  it was found"""

    def __init__(
        self,
        *,
        value: google.protobuf.any_pb2.Any | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_value", b"_value", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_value", b"_value", "value", b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_value", b"_value"]) -> typing.Literal["value"] | None: ...

global___TryGetValueResponse = TryGetValueResponse

@typing.final
class SetValueRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PANEL_ID_FIELD_NUMBER: builtins.int
    VALUE_ID_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    NOTIFY_FIELD_NUMBER: builtins.int
    panel_id: builtins.str
    """Unique ID of the panel"""
    value_id: builtins.str
    """Unique ID of the value"""
    notify: builtins.bool
    """Notify other clients of this new value"""
    @property
    def value(self) -> google.protobuf.any_pb2.Any:
        """The value"""

    def __init__(
        self,
        *,
        panel_id: builtins.str = ...,
        value_id: builtins.str = ...,
        value: google.protobuf.any_pb2.Any | None = ...,
        notify: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["notify", b"notify", "panel_id", b"panel_id", "value", b"value", "value_id", b"value_id"]) -> None: ...

global___SetValueRequest = SetValueRequest

@typing.final
class SetValueResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___SetValueResponse = SetValueResponse
