# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ni/panels/v1/panel_types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eni/panels/v1/panel_types.proto\x12\x0cni.panels.v1\" \n\x0e\x42oolCollection\x12\x0e\n\x06values\x18\x01 \x03(\x08\"&\n\x14\x42yteStringCollection\x12\x0e\n\x06values\x18\x01 \x03(\x0c\"!\n\x0f\x46loatCollection\x12\x0e\n\x06values\x18\x01 \x03(\x01\"\x1f\n\rIntCollection\x12\x0e\n\x06values\x18\x01 \x03(\x12\"\"\n\x10StringCollection\x12\x0e\n\x06values\x18\x01 \x03(\tBu\n\x10\x63om.ni.panels.v1B\x0bPanelsProtoP\x01Z\x08panelsv1\xf8\x01\x01\xa2\x02\x04NIPS\xaa\x02\x1dNationalInstruments.Panels.V1\xca\x02\x0cNI\\Panels\\V1\xea\x02\x0eNI::Panels::V1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ni.panels.v1.panel_types_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\020com.ni.panels.v1B\013PanelsProtoP\001Z\010panelsv1\370\001\001\242\002\004NIPS\252\002\035NationalInstruments.Panels.V1\312\002\014NI\\Panels\\V1\352\002\016NI::Panels::V1'
  _BOOLCOLLECTION._serialized_start=48
  _BOOLCOLLECTION._serialized_end=80
  _BYTESTRINGCOLLECTION._serialized_start=82
  _BYTESTRINGCOLLECTION._serialized_end=120
  _FLOATCOLLECTION._serialized_start=122
  _FLOATCOLLECTION._serialized_end=155
  _INTCOLLECTION._serialized_start=157
  _INTCOLLECTION._serialized_end=188
  _STRINGCOLLECTION._serialized_start=190
  _STRINGCOLLECTION._serialized_end=224
# @@protoc_insertion_point(module_scope)
