"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class StreamlitPanelConfiguration(google.protobuf.message.Message):
    """Pack this into PanelService.StartPanelRequest.panel_configuration to start a Streamlit panel."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PANEL_SCRIPT_PATH_FIELD_NUMBER: builtins.int
    PYTHON_PATH_FIELD_NUMBER: builtins.int
    panel_script_path: builtins.str
    """Absolute path of the streamlit script file on disk, or network path to the file. This must end in ".py"."""
    python_path: builtins.str
    """Path to the python interpreter to use for running the streamlit script."""
    def __init__(
        self,
        *,
        panel_script_path: builtins.str = ...,
        python_path: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["panel_script_path", b"panel_script_path", "python_path", b"python_path"]) -> None: ...

global___StreamlitPanelConfiguration = StreamlitPanelConfiguration
