name: Run unit tests

on:
  workflow_call:
  workflow_dispatch:

env:
  POETRY_VERSION: 1.8.2

jobs:
  run_unit_tests:
    name: Run unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: [3.9, '3.10', 3.11, 3.12, 3.13]
      # Fail-fast skews the pass/fail ratio and seems to make pytest produce
      # incomplete JUnit XML results.
      fail-fast: false
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      - name: Restore cached virtualenv
        uses: actions/cache/restore@v4
        id: restore-nipanel
        with:
          path: .venv
          key: nipanel-${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('poetry.lock') }}
      - name: Install nipanel
        run: poetry install -v
      - name: Save cached virtualenv
        uses: actions/cache/save@v4
        if: steps.restore-nipanel.outputs.cache-hit != 'true'
        with:
          path: .venv
          key: ${{ steps.restore-nipanel.outputs.cache-primary-key }}
      - name: Run unit tests and code coverage
        run: poetry run pytest ./tests/unit -v --cov=nipanel --junitxml=test_results/nipanel-${{ matrix.os }}-py${{ matrix.python-version }}.xml
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test_results_unit_${{ matrix.os }}_py${{ matrix.python-version }}
          path: ./test_results/*.xml
        if: always()
